name: Мой первый CI/CD

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Проверяем что всё работает
        run: echo "Код запушен! CI/CD работает!"
        
      - name: Показываем файлы
        run: ls -la
