name: Мой первый CI/CD

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Проверяем bash скрипт на ошибки
        run: bash -n check.sh
        
      - name: Запускаем скрипт
        run: bash check.sh
        
      - name: Показываем отчёт
        run: cat report_*.txt
